spring:
  servlet:
    multipart:
      max-file-size: '10MB'
      max-request-size: '10MB'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://plugger.postgres.database.azure.com:5432/db_fw_auth_service?user=plugger&password=password123-&sslmode=require
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      show-sql: 'true'
      ddl-auto: update
  security:
    user:
      name: user
      password: password
  application:
    name: fw-file-service
eureka:
  client:
    serviceUrl:
      defaultZone: https://fw-discovery-server.azurewebsites.net/eureka
  instance:
    hostname: fw-auth-service.azurewebsites.net
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}
security:
  user:
    password: ${eureka.password}

server:
  error:
    include-message: always