spring:
  servlet:
    multipart:
      max-file-size: '10MB'
      max-request-size: '10MB'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      show-sql: 'true'
      ddl-auto: update
  security:
    user:
      name: user
      password: password
  application:
    name: fw-file-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka/
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}
security:
  user:
    password: ${eureka.password}

server:
  error:
    include-message: always